### PR TITLE
Fix #9; add a blacklist for wind generation in the config file

### LINKED ISSUE #9: [Suggestion] Wind Generator Dimension Blacklist
Good day! As of right now, anyone can plop a wind generator in any dimension and it will work. This is most ridiculous in a scenario like Galacticraft, where you can place a wind generator on the Asteroid dimension and get power. Any chance we can get a blacklist for worlds where the wind generator will not work?

Thanks for the consideration, and good luck on the fork.

### PR DESCRIPTION
**Pull request by dizzyd**

### CODE REVIEW

**Comment by pupnewfster** [comment]
Should this be using the dimension registry names rather than the id numbers?

**Comment by DoctorMacc** [comment]
In my experience of perusing through mod configs, the convention for such blacklists is to use the dimension ID rather than a registry name.

(In my opinion it's much easier to find a dimension ID than a registry name)

**Comment by pupnewfster** [comment]
I think registry names is better given iirc when I was somewhat following the development of sevtech they had to at some point have a few mods switch from dimension ids to registry names due to having quite a few issues when they were using ids. Also going forward with how numerical ids have been slowly getting phased out of MC I think the registry names are better.

I am not opposed however to making a command that lists, `Name, Dimension ID, Dimension Registry Name` or something like that. In fact that would probably make configuring it even easier for people.

**Comment by dizzyd** [comment]
After some discussion, @pupnewfster and I decided to stick with the dimension IDs, in part because it ensures that it we don't have to somehow figure out when ALL mods have registered their dimensions and post process names into IDs (since at runtime, we only get an ID). 

I've opened #30 to provide a subcommand to make it easier to find the IDs in question.

**Pull request merged**
