### PR TITLE
use oredict in mekanism tools

### PR DESCRIPTION
**Pull request by temp1011**
It would probably be good to move things commonly oredicted to `_constants` in generators and mekanism too.

### CODE REVIEW

**Comment by pupnewfster** [comment]
Couple things, one (if you have not already) make sure to test at least by looking through jei that all the recipes are still there.
Secondly, (other than I am not sure if it is a default forge oredict), what is the risk of using `gemLapis` for lapis?
Finally, it may be easier to read the constants if they are formatted such as `INGOT_BRONZE` rather than `INGOTBRONZE` especially for things like refined glowstone.

**Comment by temp1011** [comment]
The recipes looked OK but I'll have another look. I wasn't sure about lapis because I assume it's oredicted to lots of blue dyes which wouldn't be a good ingredient for tools.

**Comment by pupnewfster** [comment]
> The recipes looked OK but I'll have another look. I wasn't sure about lapis because I assume it's oredicted to lots of blue dyes which wouldn't be a good ingredient for tools.

Lapis tends to have three ore dictionary entries I usually see:
```
gemLapis
dyeBlue
dye
```

**Comment by temp1011** [comment]
That makes more sense. Hopefully everything is a bit clearer now with the underscores added.

**Comment by dizzyd** [comment]
Looks good to me.

**Pull request merged**
