### PR TITLE
Repeated bulk

### PR DESCRIPTION
**Pull request by temp1011**
## Changes proposed in this pull request:
Cleanup and simplification of multiple models.
Note that creative gas tank is no longer a darker shade than the others.
I need to look into the models being rendered in code to port the reduced textures to them and also see if they are optimal (FastTESR, baked correctly etc)

### CODE REVIEW

**Comment by pupnewfster** [comment]
Not sure if this is caused by this PR or not but they probably should be fixed:
The top of the creative gas tank looks different than the other tanks in terms of shading.
image

(The top corner is darker for some reason).

Also when looking into the laser amplifier from a side with a whole on it the inside is transparent in places 
image

The same thing happens with the tractor beam.

You broke formatting in `models/blocks/fluid_tank.json`

**Comment by temp1011** [comment]
Sadly I really don't have the skill to do textures (even darkening one of the other ones) so the gas tank valves will be difficult. Not sure what causes the transparent side problem, I tried a couple things to solve it but they didn't seem to work. It does also happen on master FWIW.

**Comment by pupnewfster** [comment]
> Sadly I really don't have the skill to do textures (even darkening one of the other ones) so the gas tank valves will be difficult. Not sure what causes the transparent side problem, I tried a couple things to solve it but they didn't seem to work. It does also happen on master FWIW.

I mean even just manually editting the pixels in paint so that the darkest one is in the middle the semi dark one (current middle one) is on the center sides, and then the corners are the light ones would be fine. The shades don't have to match exactly I more meant the which ones are darker which ones are not.

**Comment by temp1011** [comment]
I'll have a try

**Comment by pupnewfster** [comment]
The valve does look a lot better now, (at least compared to how it did in my screenshot above). Still trying to figure out why the frame doesn't render on the inside of the amplifier and tractor beam.

**Comment by temp1011** [comment]
I think we may need to have a cuboid on each side for the frame. Then it will work.

**Comment by pupnewfster** [comment]
Going to merge this, and have the frame fix be in another PR as it is an issue before this PR as well.

**Pull request merged**
