### PR TITLE
Reduce empty space in texture map

### PR DESCRIPTION
**Pull request by temp1011**
Texture map after this (before is the same as my other PR):
after
This is just the textures that could be immediately shrunk or didn't require too much moving elements around. There's a lot more that's possible but it will be harder to do. 

Sadly the formatting on the model json files got messed up by this, I'm not really sure what's best to do to fix that.

Moving from a 256x256 texture to a 128x128 saves 49152 pixels, which is 192 16x16 textures. Given that I've done this 6 times that means a texture atlas of the same size can hold 1152 more small textures, which is quite a nice saving IMO :smile: .

I've checked the blocks out in world and they all seem to be fine but you may want to check for yourselves.

### CODE REVIEW

**Comment by pupnewfster** [comment]
This only removes the empty space, it doesn't actually change the texture resolution right?

Also I recommend we hold off on merging this until #43 is merged, as to make sure it doesn't cause any issues with item rendering. (Given a bunch of it is done via the Java Model files, so we need to make sure it still grabs the correct parts of the textures.). As getting rid of the hack that is the current way some items are rendered is higher priority than saving some space. (Though good job on this that is a lot of space saved)

**Comment by temp1011** [comment]
Makes sense to block on #43. The resolution of textures is the same for now, there's a lot to do to reduce atlas size nore before comsidering that (apart from maybe things like the huge pipes)

**Comment by pupnewfster** [comment]
Sounds good, I just wanted to make sure the resolution didn't get touched.

**Comment by pupnewfster** [comment]
Thinking about it another way we can improve the map size at some point is convert the factories to use tints like the tanks do. That way we don't need a different texture for each tier. (And maybe also do a similar thing for the tubes, and activated/unactivated machines.

**Comment by temp1011** [comment]
Yeah, gas tanks don't even use tints at the moment. Lots of textures also have duplicated/very similar elements inside (eg - fluid tank should just need one side and one top texture really). I think there were quite a few rotated duplicated textures too.

Once 256*256 textures are reduced the impact becomes a lot less of a problem though.

**Comment by pupnewfster** [comment]
Now that #43 is merged you should merge master back into this branch, and test to make sure things still render properly as items.

**Comment by temp1011** [comment]
The logistical sorter doesn't switch to it's on texture on this branch or master as far as I can tell. Other than that, I can't see any differences.

**Comment by pupnewfster** [comment]
If you mean in item form, that is because the logistical sorter doesn't use one of the special rendering types. Maybe at some point we can switch it to them, I just see no reason to bother at the moment as it works fine with the normal model system. If you mean the placed logistical sorter no idea why that is the case.

**Comment by temp1011** [comment]
I don't see the block change in world, but I also have no idea why it doesn't

**Comment by pupnewfster** [comment]
I will look into it before the next release, and try to figure out when it broke/if it has just always been broken.

**Comment by temp1011** [comment]
It's a shame the json got so bloated but other than that hopefully this gives a nice boost.

**Pull request merged**
